export enum SorterOption {
    TIME_ASC ="TIME_ASC",
    TIME_DESC ="TIME_DESC",
    INGREDIENTS_ASC ="INGREDIENTS_ASC",
    INGREDIENTS_DESC ="INGREDIENTS_DESC",
    ALPHABETICALLY="ALPHABETICALLY",
}